README: Execute commands under pipenv (#302)
* Prepend `pipenv run ` to command lines

Without it, they don't use the virtualenv and don't find dependencies:

$ ./rose-server
Traceback (most recent call last):
  File "./rose-server", line 3, in <module>
    from rose.server import main
  File "/home/bpaskinc/ROSE/rose/server/main.py", line 4, in <module>
    from twisted.internet import reactor
ImportError: No module named twisted.internet

* Reword to open `pipenv shell` instead of prepending `pipenv run`